python3 main.py report realm/realm-java
python3 main.py report rstudio/rstudio
python3 main.py report JetBrains/intellij-community
python3 main.py report SonarSource/sonarqube
python3 main.py report crashub/crash
python3 main.py report jeeeyul/eclipse-themes
python3 main.py report oblac/jodd
python3 main.py report glyptodon/guacamole-client
python3 main.py report raphw/byte-buddy
python3 main.py report Athou/commafeed
python3 main.py report fabric8io/fabric8
python3 main.py report puniverse/quasar
python3 main.py report dreamhead/moco
python3 main.py report vaadin/vaadin
python3 main.py report gradle/gradle
python3 main.py report JetBrains/MPS
python3 main.py report SecUpwN/Android-IMSI-Catcher-Detector
python3 main.py report BroadleafCommerce/BroadleafCommerce
python3 main.py report datastax/java-driver
python3 main.py report hibernate/hibernate-orm
python3 main.py report apache/cassandra
python3 main.py report liferay/liferay-portal
python3 main.py report HubSpot/Singularity
python3 main.py report CyanogenMod/android_frameworks_base
python3 main.py report elastic/elasticsearch
python3 main.py report kuujo/copycat
python3 main.py report FasterXML/jackson-databind
python3 main.py report Alluxio/alluxio
python3 main.py report orientechnologies/orientdb
python3 main.py report VoltDB/voltdb
python3 main.py report undertow-io/undertow
python3 main.py report spring-projects/spring-data-rest
python3 main.py report checkstyle/checkstyle
python3 main.py report eclipse/vert.x
python3 main.py report droolsjbpm/drools
python3 main.py report spring-projects/spring-boot
python3 main.py report belaban/JGroups
python3 main.py report hierynomus/sshj
python3 main.py report nutzam/nutz
python3 main.py report facebook/buck
python3 main.py report processing/processing
python3 main.py report linkedin/rest.li
python3 main.py report codinguser/gnucash-android
python3 main.py report Netflix/eureka
python3 main.py report google/closure-compiler
python3 main.py report crate/crate
python3 main.py report wordpress-mobile/WordPress-Android
python3 main.py report infinispan/infinispan
python3 main.py report geoserver/geoserver
python3 main.py report graphhopper/graphhopper
python3 main.py report brianfrankcooper/YCSB
python3 main.py report bennidi/mbassador
python3 main.py report real-logic/Aeron
python3 main.py report GoClipse/goclipse
python3 main.py report restlet/restlet-framework-java
python3 main.py report BuildCraft/BuildCraft
python3 main.py report bumptech/glide
python3 main.py report robovm/robovm
python3 main.py report netty/netty
python3 main.py report killbill/killbill
python3 main.py report eclipse/jetty.project
python3 main.py report Graylog2/graylog2-server
python3 main.py report open-keychain/open-keychain
python3 main.py report hazelcast/hazelcast
python3 main.py report jfinal/jfinal
python3 main.py report jberkel/sms-backup-plus
python3 main.py report AsyncHttpClient/async-http-client
python3 main.py report square/okhttp
python3 main.py report spring-projects/spring-integration
python3 main.py report grails/grails-core
python3 main.py report apache/pig
python3 main.py report neo4j/neo4j
python3 main.py report rackerlabs/blueflood
python3 main.py report antlr/antlr4
python3 main.py report k9mail/k-9
python3 main.py report baasbox/baasbox
python3 main.py report apache/camel
python3 main.py report spring-projects/spring-framework
python3 main.py report eucalyptus/eucalyptus
python3 main.py report apache/tomcat
python3 main.py report liferay/liferay-plugins
python3 main.py report querydsl/querydsl
python3 main.py report osmandapp/Osmand
python3 main.py report phishman3579/java-algorithms-implementation
python3 main.py report codefollower/Lealone
python3 main.py report SlimeKnights/TinkersConstruct
python3 main.py report joel-costigliola/assertj-core
python3 main.py report mockito/mockito
python3 main.py report brettwooldridge/HikariCP
python3 main.py report ratpack/ratpack
python3 main.py report languagetool-org/languagetool
python3 main.py report opentripplanner/OpenTripPlanner
python3 main.py report apache/hive
python3 main.py report mrniko/redisson
python3 main.py report wicketstuff/core
python3 main.py report apache/drill
python3 main.py report scobal/seyren
python3 main.py report mongodb/morphia
python3 main.py report facebook/presto
python3 main.py report go-lang-plugin-org/go-lang-idea-plugin
python3 main.py report mongodb/mongo-java-driver
python3 main.py report openhab/openhab
python3 main.py report wildfly/wildfly
python3 main.py report Netflix/zuul
python3 main.py report jankotek/MapDB
python3 main.py report springfox/springfox
python3 main.py report structr/structr
python3 main.py report WhisperSystems/Signal-Android
python3 main.py report bitcoinj/bitcoinj
python3 main.py report jersey/jersey
python3 main.py report apache/giraph
python3 main.py report spring-projects/spring-data-neo4j
python3 main.py report aws/aws-sdk-java
python3 main.py report gwtproject/gwt
python3 main.py report libgdx/libgdx
python3 main.py report redsolution/xabber-android
python3 main.py report facebook/facebook-android-sdk
python3 main.py report QuantumBadger/RedReader
python3 main.py report cbeust/testng
python3 main.py report spring-projects/spring-data-jpa
python3 main.py report deeplearning4j/deeplearning4j
python3 main.py report apache/zookeeper
python3 main.py report AntennaPod/AntennaPod
python3 main.py report koush/AndroidAsync
python3 main.py report Activiti/Activiti
python3 main.py report droolsjbpm/jbpm
python3 main.py report katzer/cordova-plugin-local-notifications
python3 main.py report square/wire
python3 main.py report jboss-developer/jboss-eap-quickstarts
python3 main.py report google/truth
python3 main.py report slapperwan/gh4a
python3 main.py report abarisain/dmix
python3 main.py report spring-projects/spring-data-mongodb
python3 main.py report google/guava
python3 main.py report cucumber/cucumber-jvm
python3 main.py report google/j2objc
python3 main.py report tomahawk-player/tomahawk-android
python3 main.py report novoda/android-demos
python3 main.py report siacs/Conversations
python3 main.py report orfjackal/retrolambda
python3 main.py report reactor/reactor
python3 main.py report Jasig/cas
python3 main.py report google/auto
python3 main.py report spotify/helios
python3 main.py report thymeleaf/thymeleaf
python3 main.py report SimonVT/schematic
python3 main.py report github/android
python3 main.py report cgeo/cgeo
python3 main.py report square/javapoet
python3 main.py report spring-projects/spring-security
python3 main.py report jline/jline2
python3 main.py report plutext/docx4j
python3 main.py report Netflix/feign
python3 main.py report geometer/FBReaderJ
python3 main.py report zeromq/jeromq
python3 main.py report AdoptOpenJDK/jitwatch
python3 main.py report jMonkeyEngine/jmonkeyengine
python3 main.py report loopj/android-async-http
python3 main.py report greenrobot/greenDAO
python3 main.py report xetorthio/jedis
python3 main.py report NLPchina/ansj_seg
python3 main.py report ignatov/intellij-erlang
python3 main.py report MovingBlocks/Terasology
python3 main.py report JetBrains/intellij-plugins
python3 main.py report PhilJay/MPAndroidChart
python3 main.py report RoboBinding/RoboBinding
python3 main.py report dropwizard/metrics
python3 main.py report jenkinsci/workflow-plugin
python3 main.py report Atmosphere/atmosphere
python3 main.py report skylot/jadx
python3 main.py report jOOQ/jOOQ
python3 main.py report selendroid/selendroid
python3 main.py report alibaba/druid
python3 main.py report spring-projects/spring-roo
python3 main.py report addthis/hydra
python3 main.py report clojure/clojure
python3 main.py report ReactiveX/RxJava
python3 main.py report cwensel/cascading
python3 main.py report bitfireAT/davdroid
python3 main.py report square/mortar
python3 main.py report spring-projects/spring-hateoas
python3 main.py report HdrHistogram/HdrHistogram
python3 main.py report JoanZapata/android-iconify
python3 main.py report Netflix/genie
python3 main.py report jayway/rest-assured

