python3 main.py detector realm/realm-java
python3 main.py detector rstudio/rstudio
python3 main.py detector JetBrains/intellij-community
python3 main.py detector SonarSource/sonarqube
python3 main.py detector crashub/crash
python3 main.py detector jeeeyul/eclipse-themes
python3 main.py detector oblac/jodd
python3 main.py detector glyptodon/guacamole-client
python3 main.py detector raphw/byte-buddy
python3 main.py detector Athou/commafeed
python3 main.py detector fabric8io/fabric8
python3 main.py detector puniverse/quasar
python3 main.py detector dreamhead/moco
python3 main.py detector vaadin/vaadin
python3 main.py detector gradle/gradle
python3 main.py detector JetBrains/MPS
python3 main.py detector SecUpwN/Android-IMSI-Catcher-Detector
python3 main.py detector BroadleafCommerce/BroadleafCommerce
python3 main.py detector datastax/java-driver
python3 main.py detector hibernate/hibernate-orm
python3 main.py detector apache/cassandra
python3 main.py detector liferay/liferay-portal
python3 main.py detector HubSpot/Singularity
python3 main.py detector CyanogenMod/android_frameworks_base
python3 main.py detector elastic/elasticsearch
python3 main.py detector kuujo/copycat
python3 main.py detector FasterXML/jackson-databind
python3 main.py detector Alluxio/alluxio
python3 main.py detector orientechnologies/orientdb
python3 main.py detector VoltDB/voltdb
python3 main.py detector undertow-io/undertow
python3 main.py detector spring-projects/spring-data-rest
python3 main.py detector checkstyle/checkstyle
python3 main.py detector eclipse/vert.x
python3 main.py detector droolsjbpm/drools
python3 main.py detector spring-projects/spring-boot
python3 main.py detector belaban/JGroups
python3 main.py detector hierynomus/sshj
python3 main.py detector nutzam/nutz
python3 main.py detector facebook/buck
python3 main.py detector processing/processing
python3 main.py detector linkedin/rest.li
python3 main.py detector codinguser/gnucash-android
python3 main.py detector Netflix/eureka
python3 main.py detector google/closure-compiler
python3 main.py detector crate/crate
python3 main.py detector wordpress-mobile/WordPress-Android
python3 main.py detector infinispan/infinispan
python3 main.py detector geoserver/geoserver
python3 main.py detector graphhopper/graphhopper
python3 main.py detector brianfrankcooper/YCSB
python3 main.py detector bennidi/mbassador
python3 main.py detector real-logic/Aeron
python3 main.py detector GoClipse/goclipse
python3 main.py detector restlet/restlet-framework-java
python3 main.py detector BuildCraft/BuildCraft
python3 main.py detector bumptech/glide
python3 main.py detector robovm/robovm
python3 main.py detector netty/netty
python3 main.py detector killbill/killbill
python3 main.py detector eclipse/jetty.project
python3 main.py detector Graylog2/graylog2-server
python3 main.py detector open-keychain/open-keychain
python3 main.py detector hazelcast/hazelcast
python3 main.py detector jfinal/jfinal
python3 main.py detector jberkel/sms-backup-plus
python3 main.py detector AsyncHttpClient/async-http-client
python3 main.py detector square/okhttp
python3 main.py detector spring-projects/spring-integration
python3 main.py detector grails/grails-core
python3 main.py detector apache/pig
python3 main.py detector neo4j/neo4j
python3 main.py detector rackerlabs/blueflood
python3 main.py detector antlr/antlr4
python3 main.py detector k9mail/k-9
python3 main.py detector baasbox/baasbox
python3 main.py detector apache/camel
python3 main.py detector spring-projects/spring-framework
python3 main.py detector eucalyptus/eucalyptus
python3 main.py detector apache/tomcat
python3 main.py detector liferay/liferay-plugins
python3 main.py detector querydsl/querydsl
python3 main.py detector osmandapp/Osmand
python3 main.py detector phishman3579/java-algorithms-implementation
python3 main.py detector codefollower/Lealone
python3 main.py detector SlimeKnights/TinkersConstruct
python3 main.py detector joel-costigliola/assertj-core
python3 main.py detector mockito/mockito
python3 main.py detector brettwooldridge/HikariCP
python3 main.py detector ratpack/ratpack
python3 main.py detector languagetool-org/languagetool
python3 main.py detector opentripplanner/OpenTripPlanner
python3 main.py detector apache/hive
python3 main.py detector mrniko/redisson
python3 main.py detector wicketstuff/core
python3 main.py detector apache/drill
python3 main.py detector scobal/seyren
python3 main.py detector mongodb/morphia
python3 main.py detector facebook/presto
python3 main.py detector go-lang-plugin-org/go-lang-idea-plugin
python3 main.py detector mongodb/mongo-java-driver
python3 main.py detector openhab/openhab
python3 main.py detector wildfly/wildfly
python3 main.py detector Netflix/zuul
python3 main.py detector jankotek/MapDB
python3 main.py detector springfox/springfox
python3 main.py detector structr/structr
python3 main.py detector WhisperSystems/Signal-Android
python3 main.py detector bitcoinj/bitcoinj
python3 main.py detector jersey/jersey
python3 main.py detector apache/giraph
python3 main.py detector spring-projects/spring-data-neo4j
python3 main.py detector aws/aws-sdk-java
python3 main.py detector gwtproject/gwt
python3 main.py detector libgdx/libgdx
python3 main.py detector redsolution/xabber-android
python3 main.py detector facebook/facebook-android-sdk
python3 main.py detector QuantumBadger/RedReader
python3 main.py detector cbeust/testng
python3 main.py detector spring-projects/spring-data-jpa
python3 main.py detector deeplearning4j/deeplearning4j
python3 main.py detector apache/zookeeper
python3 main.py detector AntennaPod/AntennaPod
python3 main.py detector koush/AndroidAsync
python3 main.py detector Activiti/Activiti
python3 main.py detector droolsjbpm/jbpm
python3 main.py detector katzer/cordova-plugin-local-notifications
python3 main.py detector square/wire
python3 main.py detector jboss-developer/jboss-eap-quickstarts
python3 main.py detector google/truth
python3 main.py detector slapperwan/gh4a
python3 main.py detector abarisain/dmix
python3 main.py detector spring-projects/spring-data-mongodb
python3 main.py detector google/guava
python3 main.py detector cucumber/cucumber-jvm
python3 main.py detector google/j2objc
python3 main.py detector tomahawk-player/tomahawk-android
python3 main.py detector novoda/android-demos
python3 main.py detector siacs/Conversations
python3 main.py detector orfjackal/retrolambda
python3 main.py detector reactor/reactor
python3 main.py detector Jasig/cas
python3 main.py detector google/auto
python3 main.py detector spotify/helios
python3 main.py detector thymeleaf/thymeleaf
python3 main.py detector SimonVT/schematic
python3 main.py detector github/android
python3 main.py detector cgeo/cgeo
python3 main.py detector square/javapoet
python3 main.py detector spring-projects/spring-security
python3 main.py detector jline/jline2
python3 main.py detector plutext/docx4j
python3 main.py detector Netflix/feign
python3 main.py detector geometer/FBReaderJ
python3 main.py detector zeromq/jeromq
python3 main.py detector AdoptOpenJDK/jitwatch
python3 main.py detector jMonkeyEngine/jmonkeyengine
python3 main.py detector loopj/android-async-http
python3 main.py detector greenrobot/greenDAO
python3 main.py detector xetorthio/jedis
python3 main.py detector NLPchina/ansj_seg
python3 main.py detector ignatov/intellij-erlang
python3 main.py detector MovingBlocks/Terasology
python3 main.py detector JetBrains/intellij-plugins
python3 main.py detector PhilJay/MPAndroidChart
python3 main.py detector RoboBinding/RoboBinding
python3 main.py detector dropwizard/metrics
python3 main.py detector jenkinsci/workflow-plugin
python3 main.py detector Atmosphere/atmosphere
python3 main.py detector skylot/jadx
python3 main.py detector jOOQ/jOOQ
python3 main.py detector selendroid/selendroid
python3 main.py detector alibaba/druid
python3 main.py detector spring-projects/spring-roo
python3 main.py detector addthis/hydra
python3 main.py detector clojure/clojure
python3 main.py detector ReactiveX/RxJava
python3 main.py detector cwensel/cascading
python3 main.py detector bitfireAT/davdroid
python3 main.py detector square/mortar
python3 main.py detector spring-projects/spring-hateoas
python3 main.py detector HdrHistogram/HdrHistogram
python3 main.py detector JoanZapata/android-iconify
python3 main.py detector Netflix/genie
python3 main.py detector jayway/rest-assured

